### PR TITLE
chore: update bl

### PR DESCRIPTION
**Pull request by hugomrdias**
This PR updates bl dependency to the latest version

### CODE REVIEW

**Comment by hugomrdias** [comment]
ping

**Comment by hugomrdias** [comment]
ping

**Comment by mafintosh** [comment]
hi, thanks for the ping. do you know what the major upgrade breaks?

**Comment by hugomrdias** [comment]
hopefully nothing :) 
https://github.com/rvagg/bl/pull/55 
added support for readUIntLE / readUIntBE / readIntLE / readIntBE

**Comment by mafintosh** [comment]
In master

**Pull request closed without merging**
