### PR TITLE
always pass emptyStream when type is directory

### LINKED ISSUE #68: Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
I have a tarball from the registry (and others) that consistency fail with invalid tar header errors but are valid archive.

To replicate
1. `wget https://registry.npmjs.org/eslint-config-metashop/-/eslint-config-metashop-1.5.0.tgz`

2. Use the following test case
```
const Tar = require('tar-stream');
const Gunzip = require('gunzip-maybe');
const Fs = require('fs');

const gunzip = Gunzip();
const extract = Tar.extract();
const inputFile = Fs.createReadStream(process.argv[2]);

extract.on('error', function (err) {
  console.log(err);
});

extract.on('entry', function (header, stream, callback) {
  stream.on('end', function () {
    return callback()
  });
  stream.resume()
});

inputFile.on('error', function (err) {
  console.log(err)
});

inputFile.pipe(gunzip).pipe(extract);
```

3. node test.js eslint-config-metashop-1.5.0.tgz

The error I get is something like
```
Error: Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?
    at Object.exports.decode (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/headers.js:265:40)
    at Extract.onheader [as _onparse] (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:124:39)
    at Extract._write (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:248:8)
    at Extract._continue (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:212:28)
    at oncontinue (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:65:10)
    at Extract.onheader [as _onparse] (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:132:7)
    at Extract._write (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:248:8)
    at Extract._continue (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:212:28)
    at oncontinue (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:65:10)
    at Extract.onheader [as _onparse] (/Users/adam_baldwin/Documents/projects/tarHash/node_modules/tar-stream/extract.js:132:7)
```

Doing some debugging it appears that the stream has advanced too far into the archive and the data it's trying to pass to parse the header is actually file contents, that's as far as we've got so far.

### PR DESCRIPTION
**Pull request by nlf**
closes #68 

simplest possible fix without losing information

### CODE REVIEW

**Comment by mafintosh** [comment]
Curious, you har a tar that has a directory entry with size but no content in the tar? Sounds invalid, but I can merge this anyway. Just want to make sure I'm not missing anything.

**Comment by nlf** [comment]
as i mentioned in #68:

> On systems where disk allocation is performed on a directory basis, the size field will contain the maximum number of bytes (which may be rounded to the nearest disk block allocation unit) which the directory may hold. A size field of zero indicates no such limiting. Systems which do not support limiting in this manner should ignore the size field.

it just so happens we came across a tarball that was created on a system that allows for this, and since tar-stream doesn't write directly to disk anyway it seemed the correct behavior was to disregard the size field for directories.

**Comment by mafintosh** [comment]
Makes sense. I'll release when I get back from lunch

**Comment by mafintosh** [comment]
1.5.4, Thanks!

**Pull request merged**
