### PR TITLE
when parsing base256 encoded sizes, include all 12 bits

### LINKED ISSUE #61: large file issue
I've got a tar file with a few large (>10GB) files in it.  When tar-stream gets to the first big file, it chokes with an `Invalid tar header` error.  I can't provide the tar file itself, but hopefully this is helpful:

it hums along through a few small files, and then it hits the header for the first large file (provided here base64 encoded):

```
cnMtZHMwNTk1NDhfMjAxNi0xMS0yOFQxOTAwMTEuMDAwWi9nb29kZWdncy1nYXJiYW56by9vcmRlcl9pdGVtcy5ic29uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAwMDA2NDQAMDAwMTc1MQAwMDAxNzUxAIAAAAAAAAACfZ6FHjEzMDE3MTAxMDc1ADAyMzMxNgAgMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB1c3RhciAgAG1hZG1pbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYWRtaW5zAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
```

which it claims to parse and tells me is `{name: 'rs-ds059548_2016-11-28T190011.000Z/goodeggs-garbanzo/order_items.bson', size: 2}` ... but the size according to bsdtar on OSX is `10697475358` ...

and then it chokes parsing the next tar header (presumably because it has used the entirely wrong offset).

If I can provide more data (without providing the file itself), please let me know.

### PR DESCRIPTION
**Pull request by bobzoller**
Turns out it was a simple typo -- the size field is 12 bits long, not 8.

fixes #61

### CODE REVIEW

**Comment by piranna** [comment]
Tests are failling... also, could you be able to add a test for your use case?

**Comment by bobzoller** [comment]
tests should pass this time -- more complete fix too.  I'll see about adding a test, but offhand it seems how they're written it would take me committing a 10GB fixture(?)

**Comment by bobzoller** [comment]
yeah... test wise I'm stuck unless you want to suggest something:
- a small file with a header forced into base256 encoding wouldn't have caught this bug
- I could commit/reference a 10GB fixture
- I could try to trim the header off a large tar, leaving a fixture we could parse but an invalid tarfile

**Comment by mafintosh** [comment]
Nice catch. I'll take a look at this tmw so we can get it merged.

**Comment by piranna** [comment]
> a small file with a header forced into base256 encoding wouldn't have caught this bug

Why not? According to the code it would be feasable...


> I could commit/reference a 10GB fixture

Overkill, but maybe you could craft it by replacing the file stream for one that generated on the fly 10GB of data, so there's no need to store it.


> I could try to trim the header off a large tar, leaving a fixture we could parse but an invalid tarfile

That would be feasable too, we are only interested on testing the header and not the tarfile itself, so the test can be able to catch and swallow the exception. I would implement the three tests, seems they can show different use cases :-)

**Comment by kanongil** [comment]
Can this get merged? I need large file support for my project.

Also, it is perfectly possible to create a small and valid test fixture for this, where eg. the file size is encoded as base-256.

**Comment by piranna** [comment]
@kanongil, could you be able to provide the test?

**Comment by kanongil** [comment]
@piranna I have made a PR #67 with a test containing a handcrafted file with a base-256 file size.

I have verified that it decompresses correctly using macOS tar client.

**Comment by bobzoller** [comment]
thanks @kanongil

**Comment by kanongil** [comment]
Ping?

**Comment by kanongil** [comment]
Anything else I can do to speed this along?

**Comment by mafintosh** [comment]
1.5.3 (including the test)

**Pull request merged**
