### PR TITLE
Move to `streamx` for streams, `brittle` for testing, and `b4a` for buffer operations

### PR DESCRIPTION
**Pull request by kasperisager**
Closes #134
Closes #137

### CODE REVIEW

**Comment by kasperisager** [comment]
@mafintosh This is ready for review.

**Comment by silverwind** [comment]
I see this commit is the reason for the 3.0.0 major version bump, but I wonder what exactly here is breaking?

**Comment by kasperisager** [comment]
Streamx behaves differently from Node.js streams in several ways, so as a precaution the switch was considered a major change.

**Comment by silverwind** [comment]
I see. At least for my use case (simple extraction), it looks to be compatible.

**Comment by mafintosh** [comment]
It should be fully compat, just precaution

**Comment by willm** [comment]
I'm trying to upgrade to version 3 where I use this in conjunction with the koa framework. It seems like koa behaves differently when setting the response body to a nodejs stream. In version 3 (presumably because it's no longer a node stream), koa tries to serialise Pack as json. Is there a way to convert back to a node js stream in v3?

**Pull request merged**
