### PR TITLE
Detect file type from 'mode' field & allow to stream symlinks content

### PR DESCRIPTION
**Pull request by piranna**
This pull-request allow to auto-discover the file type from the header 'mode' field if an explicit 'type' field is not defined, and also allow to set the content of symlinks streaming it's content if the header 'linkname' field is not defined. This allow pipe all the content into a tar package, for example:

```Javascript
#!/usr/bin/env node

var cpio = require('cpio-stream')
var tar  = require('tar-stream')


var extract = cpio.extract()
var pack    = tar.pack()

extract.on('entry', function(header, stream, callback)
{
  stream.pipe(pack.entry(header, callback))

  stream.resume() // auto drain
})

extract.on('finish', function()
{
  pack.finalize()
})

process.stdin.pipe(extract)
pack.pipe(process.stdout)
```

### CODE REVIEW

**Comment by mafintosh** [comment]
Oops this got messed up by a style cleanup I just did. Sorry about that.

Could you update the PR? Also if you could remove the require style changes and use Egyptian casing for functions that would be nice

``` js
function foo () {
   ...
}
```

The feature looks good though!

**Comment by piranna** [comment]
> Oops this got messed up by a style cleanup I just did. Sorry about that.

This sometimes happens :-)


> if you could remove the require style changes

What changes, the alignment or the order? The alignment is somewhat aesthetic so ok, the order is the one recomended for Node.js (taken from Python): built-ins, third-party modules and same package.


> and use Egyptian casing for functions that would be nice
> 
> function foo () {
>    ...
> }

So space after name and bracket on same line, isn't it? Ok.

(Just curious: Egyptian? It's the first time that I see that thing named! :-P So you have some link about it? :-) )

**Comment by mafintosh** [comment]
I mean the require alignment. Don't really care about the order but feel free to change it :)
Its called Egyptian because it looks like this

egypt

**Comment by piranna** [comment]
> I mean the require alignment

I'm used to do it, get's cleaner to look for them :-)


> Its called Egyptian because it looks like this

I supposed it :-) Done :-)

**Comment by piranna** [comment]
Any update on this?

**Comment by mafintosh** [comment]
Thanks! Released in 1.3.0 (sorry for the delay)

**Comment by piranna** [comment]
You are welcome! :-)

**Pull request merged**
