### PR TITLE
Ensure packed symlinks have size zero as required by GNU `tar`

### PR DESCRIPTION
**Pull request by piranna**
This should fix issues #44 and #48.

### CODE REVIEW

**Comment by mafintosh** [comment]
Really great work! Thanks a lot. Do you wanna help maintain this in general? I can add you as a co-owner.

**Comment by mafintosh** [comment]
Out in 1.5.2

**Comment by piranna** [comment]
> Do you wanna help maintain this in general? I can add you as a co-owner.

That would be an honor to me... :-D

I'm just testing this thing to see if it's fixing the issues I'm having on NodeOS, but at least now we generate tar files as gnu tar expects! :-P

**Comment by mafintosh** [comment]
Done. Thanks again for all your great contributions

**Comment by mafintosh** [comment]
Yea. tar has a crazy amount of edge cases because of buggy impls in the wild :/

**Comment by piranna** [comment]
> Done. Thanks again for all your great contributions

You are welcome :-)


> Yea. tar has a crazy amount of edge cases because of buggy impls in the wild :/

At least seems I got it fixed for my use case! :-D But as I said, seems to be a bug in gnu `tar` by doing an otherwise unnecesary check... ¬¬

**Pull request merged**
